kind: Namespace
apiVersion: v1
metadata:
  name: biodiesel-etoh-tank
  labels:
    name: biodiesel-etoh-tank
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: biodiesel-etoh-tank
  namespace: biodiesel-etoh-tank
  labels:
    app: biodiesel-etoh-tank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: biodiesel-etoh-tank
  template:
    metadata:
      labels:
        app: biodiesel-etoh-tank
    spec:
      containers:
        - name: biodiesel-etoh-tank
          image: islansilva/biodiesel-etoh-tank:0.0.2
          ports:
            - name: web
              containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: biodiesel-etoh-tank
  namespace: biodiesel-etoh-tank
spec:
  selector:
    app: biodiesel-etoh-tank
  ports:
    - port: 8080
  type: ClusterIP