kind: Namespace
apiVersion: v1
metadata:
  name: test
  labels:
    name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-player
  namespace: test
  labels:
    app: app-player
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-player
  template:
    metadata:
      labels:
        app: app-player
    spec:
      containers:
        - name: app-player
          image: biz1999/test:1.0.0
          ports:
            - name: web
              containerPort: 8080